### ISSUE TITLE
Linkinator: Check skipped links

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/volkamerlab_org#54]
Check if we need the following [skipped links in the Linkinator (CI)](https://github.com/volkamerlab/volkamerlab_org/blob/8d68c36db80bbbbb8789f38e56b29fbd173437c5/.github/workflows/ci.yaml#L38-L41):

In PR #53, I added the following links to the Linkinator:
- Exit code 403 (access forbidden): https://dx.doi.org/10.1002/ardp.202100123
- Exit code 0 (slow response): https://www.einsteinfoundation.de/en/people-projects/einstein-bih-visiting-fellows/john-chodera/       
- Exit code 0 (slow response):  https://www.einsteinfoundation.de/en/programmes/einstein-bih-visiting-fellow/

@jaimergp please let me know if this is the correct way to deal with the CI fails.

**Comment by jaimergp** [comment]
Looks fine!
